version: "3.8"

services:
  app:
    image: superklok/sliderpilerpointca:1.5.11
    build: 
      context: .
      target: prod
    ports:
      - "80:80"
    command: npm start
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production